### ISSUE TITLE
Unable to connect to MongoDB when auth disabled

### ISSUE THREAD

**Issue by simonfreeman80** [tarathep/robot-mongodb-library#1]
Hi, 
when I try to create a test case connecting to MongoDB with no auth I'm unable to insert any record

Step to reproduce:
```
*** Variables ***
&{MONGODB_CONNECT_STRING}    host=127.0.0.1   port=27017   username=   password=    database=test     collection=test

*** Test Cases ***
Test insert data into mongodb
    &{DATA}     Create Dictionary   _id=X100001      name=Tarathep      address=Thailand     phone=8888888888
    ${MSG}      InsertOne   ${MONGODB_CONNECT_STRING}    ${DATA}
    Should Be Equal    ${MSG}    INSERTED SUCCESS
```

I simply get 

`${MSG} = INSERTED ERROR`

Tested with other library works fine.
I tryed as well omitting username and password:

```
*** Variables ***
&{MONGODB_CONNECT_STRING}    host=127.0.0.1   port=27017   database=test     collection=test
```
I think problem depends on hard-coded connection string:
`  db=pymongo.MongoClient("mongodb://"+con["username"]+":"+con["password"]`

Thank you

**Comment by tarathep** [comment]
thank you for feeback to me , i will fix them on version 0.0.5  and  supported to use connection string you can try again
